# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::CarrierPickupSchedule do
  let(:client) { Usps::Client.new }
  context 'carrier_pickup_schedule' do
    it 'requires carrier_pickup_schedule_request' do
      expect { client.carrier_pickup_schedule }.to raise_error ArgumentError, /Required arguments :carrier_pickup_schedule_request missing/
    end
  end
end
