# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::CityStateLookup do
  let(:client) { Usps::Client.new }
  context 'city_state_lookup' do
    it 'requires city_state_lookup_request' do
      expect { client.city_state_lookup }.to raise_error ArgumentError, /Required arguments :city_state_lookup_request missing/
    end
  end
end
