# frozen_string_literal: true

# This file was auto-generated by lib/tasks/api.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::EVSICancel do
  let(:client) { Usps::Client.new }
  context 'e_vsi_cancel' do
    it 'requires e_vsi_cancel_request' do
      expect { client.e_vsi_cancel }.to raise_error ArgumentError, /Required arguments :e_vsi_cancel_request missing/
    end
  end
end
