# frozen_string_literal: true

# This file was auto-generated by lib/tasks/api.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::EVSGXGGetLabel do
  let(:client) { Usps::Client.new }
  context 'e_vsgxg_get_label' do
    it 'requires e_vsgxg_get_label_request' do
      expect { client.e_vsgxg_get_label }.to raise_error ArgumentError, /Required arguments :e_vsgxg_get_label_request missing/
    end
  end
end
