# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::HFPFacilityInfo do
  let(:client) { Usps::Client.new }
  context 'hfp_facility_info' do
    it 'requires hfp_facility_info_request' do
      expect { client.hfp_facility_info }.to raise_error ArgumentError, /Required arguments :hfp_facility_info_request missing/
    end
  end
end
