# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::PTSRre do
  let(:client) { Usps::Client.new }
  context 'pts_rre' do
    it 'requires pts_rre_request' do
      expect { client.pts_rre }.to raise_error ArgumentError, /Required arguments :pts_rre_request missing/
    end
  end
end
