# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::PTSEmail do
  let(:client) { Usps::Client.new }
  context 'pts_email' do
    it 'requires pts_email_request' do
      expect { client.pts_email }.to raise_error ArgumentError, /Required arguments :pts_email_request missing/
    end
  end
end
