# frozen_string_literal: true

# This file was auto-generated by lib/tasks/api.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::PTSTPod do
  let(:client) { Usps::Client.new }
  context 'ptst_pod' do
    it 'requires ptst_pod_request' do
      expect { client.ptst_pod }.to raise_error ArgumentError, /Required arguments :ptst_pod_request missing/
    end
  end
end
