# frozen_string_literal: true

# This file was auto-generated by lib/tasks/api.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::SCAN do
  let(:client) { Usps::Client.new }
  context 'scan' do
    it 'requires scan_request' do
      expect { client.scan }.to raise_error ArgumentError, /Required arguments :scan_request missing/
    end
  end
end
