# frozen_string_literal: true

# This file was auto-generated by lib/tasks/api.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::SundayHolidayAvailability do
  let(:client) { Usps::Client.new }
  context 'sunday_holiday_availability' do
    it 'requires sunday_holiday_request' do
      expect { client.sunday_holiday_availability }.to raise_error ArgumentError, /Required arguments :sunday_holiday_request missing/
    end
  end
end
