# frozen_string_literal: true

# This file was auto-generated by lib/tasks/api.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::USPSReturnsLabel do
  let(:client) { Usps::Client.new }
  context 'usps_returns_label' do
    it 'requires usps_returns_label_request' do
      expect { client.usps_returns_label }.to raise_error ArgumentError, /Required arguments :usps_returns_label_request missing/
    end
  end
end
