# frozen_string_literal: true

# This file was auto-generated by lib/tasks/api.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::Verify do
  let(:client) { Usps::Client.new }
  context 'verify' do
    it 'requires address_validate_request' do
      expect { client.verify }.to raise_error ArgumentError, /Required arguments :address_validate_request missing/
    end
  end
end
