# frozen_string_literal: true

# This file was auto-generated by lib/tasks/api.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::ZipCodeLookup do
  let(:client) { Usps::Client.new }
  context 'zip_code_lookup' do
    it 'requires zip_code_lookup_request' do
      expect { client.zip_code_lookup }.to raise_error ArgumentError, /Required arguments :zip_code_lookup_request missing/
    end
  end
end
