# frozen_string_literal: true
# This file was auto-generated by lib/tasks/web.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::ZipCodeLookup do
  let(:client) { Usps::Client.new }

  context 'zip_code_lookup' do
    it 'return zip code for address' do
      response = client.zip_code_lookup({
                                          zip_code_lookup_request: {
                                            address: {
                                              city: 'Tampa',
                                              state: 'Florida',
                                              address2: '12620 Race Track Rd',
                                            },
                                          },
                                        })

      expect(response).to eq({ 'ZipCodeLookupResponse' => { 'Address' => {
                               'Address2' => '12620 RACE TRACK RD', 'City' => 'TAMPA', 'State' => 'FL', 'Zip4' => '1300', 'Zip5' => '33626'
                             } } })
    end
  end
end
